# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Python3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import numpy as np
import matplotlib.pyplot as plt

class Ui_Punto2(object):
    def setupUi(self, Punto2):
        Punto2.setObjectName("Punto2")
        Punto2.setWindowModality(QtCore.Qt.NonModal)
        Punto2.resize(488, 295)
        self.label = QtWidgets.QLabel(Punto2)
        self.label.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Punto2)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Punto2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Punto2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Punto2)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Punto2)
        self.label_6.setGeometry(QtCore.QRect(270, 10, 151, 81))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("TALLER2/IMAGENES/ecci.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.min = QtWidgets.QTextEdit(Punto2)
        self.min.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.min.setFont(font)
        self.min.setObjectName("min")
        self.label_7 = QtWidgets.QLabel(Punto2)
        self.label_7.setGeometry(QtCore.QRect(30, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.max = QtWidgets.QTextEdit(Punto2)
        self.max.setGeometry(QtCore.QRect(110, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.max.setFont(font)
        self.max.setObjectName("max")
        self.label_8 = QtWidgets.QLabel(Punto2)
        self.label_8.setGeometry(QtCore.QRect(130, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.grafica = QtWidgets.QPushButton(Punto2)
        self.grafica.setGeometry(QtCore.QRect(10, 250, 191, 31))
        self.grafica.setObjectName("grafica")
        self.graphicsView = QtWidgets.QGraphicsView(Punto2)
        self.graphicsView.setGeometry(QtCore.QRect(210, 100, 271, 181))
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox = QtWidgets.QComboBox(Punto2)
        self.comboBox.setGeometry(QtCore.QRect(10, 200, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.create_function_selector()

        self.retranslateUi(Punto2)
        QtCore.QMetaObject.connectSlotsByName(Punto2)
        self.grafica.clicked.connect(self.plot_graph)
        
    def create_function_selector(self):
        self.comboBox.addItems(["Seno", "Coseno", "Tangente", "Cotangente", "Secante", "Cosecante"])
        
    def plot_graph(self):
        # Obtener los valores ingresados
        function_index = self.comboBox.currentIndex()
        min_value = float(self.min.toPlainText())
        max_value = float(self.max.toPlainText())

        # Crear datos para graficar
        x = np.linspace(min_value, max_value, 1000)
        if function_index == 0:  # Seno
            y = np.sin(x)
        elif function_index == 1:  # Coseno
            y = np.cos(x)
        elif function_index == 2:  # Tangente
            y = np.tan(x)
        elif function_index == 3:  # Cotangente
            y = 1.0 / np.tan(x)
        elif function_index == 4:  # Secante
            y = 1.0 / np.cos(x)
        elif function_index == 5:  # Cosecante
            y = 1.0 / np.sin(x)

        # Graficar
        plt.figure()
        plt.plot(x, y)
        plt.xlabel('x')
        plt.ylabel('y')
        plt.title(" función " + self.comboBox.currentText())
        plt.grid(True)
        plt.show()


    def retranslateUi(self, Punto2):
        _translate = QtCore.QCoreApplication.translate
        Punto2.setWindowTitle(_translate("Punto2", "Punto2"))
        self.label.setText(_translate("Punto2", "Nicolas Mejia Muñoz"))
        self.label_2.setText(_translate("Punto2", "Andrés Felipe Romero Medina"))
        self.label_3.setText(_translate("Punto2", "Algoritmos de Robótica"))
        self.label_4.setText(_translate("Punto2", "Ingeniería Mecatrónica"))
        self.label_5.setText(_translate("Punto2", "2024-1"))
        self.label_7.setText(_translate("Punto2", "Minímo"))
        self.label_8.setText(_translate("Punto2", "Máximo"))
        self.grafica.setText(_translate("Punto2", "Gráfica"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Punto2 = QtWidgets.QDialog()
    ui = Ui_Punto2()
    ui.setupUi(Punto2)
    Punto2.show()
    sys.exit(app.exec_())
