
from PyQt5 import QtCore, QtGui, QtWidgets
from math import sin, cos, tan


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(366, 320)
        self.Suma = QtWidgets.QPushButton(Dialog)
        self.Suma.setGeometry(QtCore.QRect(20, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Suma.setFont(font)
        self.Suma.setObjectName("Suma")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.multipli = QtWidgets.QPushButton(Dialog)
        self.multipli.setGeometry(QtCore.QRect(20, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.multipli.setFont(font)
        self.multipli.setObjectName("multipli")
        self.resta = QtWidgets.QPushButton(Dialog)
        self.resta.setGeometry(QtCore.QRect(90, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.resta.setFont(font)
        self.resta.setObjectName("resta")
        self.div = QtWidgets.QPushButton(Dialog)
        self.div.setGeometry(QtCore.QRect(90, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.div.setFont(font)
        self.div.setObjectName("div")
        self.sin = QtWidgets.QPushButton(Dialog)
        self.sin.setGeometry(QtCore.QRect(160, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.sin.setFont(font)
        self.sin.setObjectName("sin")
        self.tan = QtWidgets.QPushButton(Dialog)
        self.tan.setGeometry(QtCore.QRect(230, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tan.setFont(font)
        self.tan.setObjectName("tan")
        self.sec = QtWidgets.QPushButton(Dialog)
        self.sec.setGeometry(QtCore.QRect(300, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.sec.setFont(font)
        self.sec.setObjectName("sec")
        self.csec = QtWidgets.QPushButton(Dialog)
        self.csec.setGeometry(QtCore.QRect(300, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.csec.setFont(font)
        self.csec.setObjectName("csec")
        self.cos = QtWidgets.QPushButton(Dialog)
        self.cos.setGeometry(QtCore.QRect(160, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cos.setFont(font)
        self.cos.setObjectName("cos")
        self.cot = QtWidgets.QPushButton(Dialog)
        self.cot.setGeometry(QtCore.QRect(230, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cot.setFont(font)
        self.cot.setObjectName("cot")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.respuesta = QtWidgets.QLabel(Dialog)
        self.respuesta.setGeometry(QtCore.QRect(80, 270, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.respuesta.setFont(font)
        self.respuesta.setText("")
        self.respuesta.setObjectName("respuesta")
        self.respuesta_2 = QtWidgets.QLabel(Dialog)
        self.respuesta_2.setGeometry(QtCore.QRect(80, 290, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.respuesta_2.setFont(font)
        self.respuesta_2.setText("")
        self.respuesta_2.setObjectName("respuesta_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(220, 20, 131, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TALLER2\IMAGENES\ecci.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(80, 140, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 140, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

        #Acción al presionar el botón en la GUI
        self.Suma.clicked.connect(self.Suma1)
        self.multipli.clicked.connect(self.multiplica)
        self.resta.clicked.connect(self.resta1)
        self.div.clicked.connect(self.divide)
        self.sin.clicked.connect(self.seno)
        self.cos.clicked.connect(self.coseno)
        self.tan.clicked.connect(self.tangente)
        self.cot.clicked.connect(self.cotangente)
        self.sec.clicked.connect(self.secante)
        self.csec.clicked.connect(self.cosecante)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Python-1"))
        self.Suma.setText(_translate("Dialog", "+"))
        self.label.setText(_translate("Dialog", "Algoritmos de Robótica "))
        self.label_2.setText(_translate("Dialog", "Nicolas Mejia Muñoz"))
        self.label_3.setText(_translate("Dialog", "Andrés Felipe Romero Medina"))
        self.label_4.setText(_translate("Dialog", "2024 - 1"))
        self.multipli.setText(_translate("Dialog", "*"))
        self.resta.setText(_translate("Dialog", "-"))
        self.div.setText(_translate("Dialog", "/"))
        self.sin.setText(_translate("Dialog", "sin"))
        self.tan.setText(_translate("Dialog", "tan"))
        self.sec.setText(_translate("Dialog", "sec"))
        self.csec.setText(_translate("Dialog", "csec"))
        self.cos.setText(_translate("Dialog", "cos"))
        self.cot.setText(_translate("Dialog", "cot"))
        self.label_5.setText(_translate("Dialog", "Número 1"))
        self.label_6.setText(_translate("Dialog", "Número 2"))
        self.label_7.setText(_translate("Dialog", "Ingeniería Mecatrónica"))
        
 #Función que se ejecuta con la acción anterior
    def Suma1(self):
        a = self.textEdit.toPlainText()
        b = self.textEdit_2.toPlainText()
        c = int(a)+int(b)
        self.respuesta.setText(str(c))
        
    def multiplica(self):
        a = self.textEdit.toPlainText()
        b = self.textEdit_2.toPlainText()
        c = int(a)*int(b)
        self.respuesta.setText(str(c))
    def resta1(self):
        a = self.textEdit.toPlainText()
        b = self.textEdit_2.toPlainText()
        c = int(a)-int(b)
        self.respuesta.setText(str(c))
    def divide(self):
        a = self.textEdit.toPlainText()
        b = self.textEdit_2.toPlainText()
        c = int(a)/int(b)
        self.respuesta.setText(str(c))
   
    def seno(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = sin(a)
        d = sin(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d)) 
    def coseno(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = cos(a)
        d = cos(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d)) 
    def tangente(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = tan(a)
        d = tan(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d)) 
    def cotangente(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = 1/tan(a)
        d = 1/tan(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d)) 
    def secante(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = 1/cos(a)
        d = 1/cos(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d)) 
        
    def cosecante(self):
        a = float(self.textEdit.toPlainText())
        b = float(self.textEdit_2.toPlainText())
        c = 1/sin(a)
        d = 1/sin(b)
        self.respuesta.setText(str(c)) 
        self.respuesta_2.setText(str(d))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
