from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TALLER2R(object):
    def setupUi(self, TALLER2R):
        TALLER2R.setObjectName("TALLER2R")
        TALLER2R.resize(588, 438)
        self.label_4 = QtWidgets.QLabel(TALLER2R)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(TALLER2R)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(TALLER2R)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(TALLER2R)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(TALLER2R)
        self.label_8.setGeometry(QtCore.QRect(340, 10, 181, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TALLER3\IMAGENES\ecci.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(TALLER2R)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DISP = QtWidgets.QWidget(TALLER2R)
        self.DISP.setGeometry(QtCore.QRect(10, 200, 271, 181))
        self.DISP.setObjectName("DISP")
        self.label_5 = QtWidgets.QLabel(TALLER2R)
        self.label_5.setGeometry(QtCore.QRect(290, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.X_LABEL = QtWidgets.QTextEdit(TALLER2R)
        self.X_LABEL.setGeometry(QtCore.QRect(310, 150, 71, 31))
        self.X_LABEL.setObjectName("X_LABEL")
        self.X_LABEL_2 = QtWidgets.QTextEdit(TALLER2R)
        self.X_LABEL_2.setGeometry(QtCore.QRect(390, 150, 71, 31))
        self.X_LABEL_2.setObjectName("X_LABEL_2")
        self.Cordenadas = QtWidgets.QPushButton(TALLER2R)
        self.Cordenadas.setGeometry(QtCore.QRect(480, 150, 71, 31))
        self.Cordenadas.setObjectName("Cordenadas")
        self.label_6 = QtWidgets.QLabel(TALLER2R)
        self.label_6.setGeometry(QtCore.QRect(300, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Area_Trabajo = QtWidgets.QPushButton(TALLER2R)
        self.Area_Trabajo.setGeometry(QtCore.QRect(340, 220, 171, 31))
        self.Area_Trabajo.setObjectName("Area_Trabajo")
        self.label_9 = QtWidgets.QLabel(TALLER2R)
        self.label_9.setGeometry(QtCore.QRect(300, 250, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Nico_boton = QtWidgets.QPushButton(TALLER2R)
        self.Nico_boton.setGeometry(QtCore.QRect(360, 270, 61, 31))
        self.Nico_boton.setObjectName("Nico_boton")
        self.Andres_boton = QtWidgets.QPushButton(TALLER2R)
        self.Andres_boton.setGeometry(QtCore.QRect(420, 270, 51, 31))
        self.Andres_boton.setObjectName("Andres_boton")
        self.label_10 = QtWidgets.QLabel(TALLER2R)
        self.label_10.setGeometry(QtCore.QRect(300, 310, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.X_LABEL_3 = QtWidgets.QTextEdit(TALLER2R)
        self.X_LABEL_3.setGeometry(QtCore.QRect(310, 330, 161, 31))
        self.X_LABEL_3.setObjectName("X_LABEL_3")
        self.Nombreperso = QtWidgets.QPushButton(TALLER2R)
        self.Nombreperso.setGeometry(QtCore.QRect(480, 330, 101, 31))
        self.Nombreperso.setObjectName("Nombreperso")
        self.label_11 = QtWidgets.QLabel(TALLER2R)
        self.label_11.setGeometry(QtCore.QRect(300, 360, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Chevroletboton = QtWidgets.QPushButton(TALLER2R)
        self.Chevroletboton.setGeometry(QtCore.QRect(300, 390, 71, 31))
        self.Chevroletboton.setObjectName("Chevroletboton")
        self.renaultboton = QtWidgets.QPushButton(TALLER2R)
        self.renaultboton.setGeometry(QtCore.QRect(380, 390, 61, 31))
        self.renaultboton.setObjectName("renaultboton")
        self.kiaboton = QtWidgets.QPushButton(TALLER2R)
        self.kiaboton.setGeometry(QtCore.QRect(450, 390, 51, 31))
        self.kiaboton.setObjectName("kiaboton")
        self.mercedeboton = QtWidgets.QPushButton(TALLER2R)
        self.mercedeboton.setGeometry(QtCore.QRect(510, 390, 71, 31))
        self.mercedeboton.setObjectName("mercedeboton")
        self.label_12 = QtWidgets.QLabel(TALLER2R)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(TALLER2R)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(TALLER2R)
        self.label_14.setGeometry(QtCore.QRect(20, 110, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(TALLER2R)
        self.label_15.setGeometry(QtCore.QRect(20, 130, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Andres_boton_2 = QtWidgets.QPushButton(TALLER2R)
        self.Andres_boton_2.setGeometry(QtCore.QRect(470, 270, 51, 31))
        self.Andres_boton_2.setObjectName("Andres_boton_2")
        self.Andres_boton_3 = QtWidgets.QPushButton(TALLER2R)
        self.Andres_boton_3.setGeometry(QtCore.QRect(310, 270, 51, 31))
        self.Andres_boton_3.setObjectName("Andres_boton_3")
        self.Andres_boton_4 = QtWidgets.QPushButton(TALLER2R)
        self.Andres_boton_4.setGeometry(QtCore.QRect(520, 270, 51, 31))
        self.Andres_boton_4.setObjectName("Andres_boton_4")

        self.retranslateUi(TALLER2R)
        QtCore.QMetaObject.connectSlotsByName(TALLER2R)

    def retranslateUi(self, TALLER2R):
        _translate = QtCore.QCoreApplication.translate
        TALLER2R.setWindowTitle(_translate("TALLER2R", "TALLER"))
        self.label_4.setText(_translate("TALLER2R", "2024 - 1"))
        self.label_7.setText(_translate("TALLER2R", "Ingeniería Mecatrónica"))
        self.label_3.setText(_translate("TALLER2R", "Andrés Felipe Romero Medina"))
        self.label_2.setText(_translate("TALLER2R", "Nicolas Mejia Muñoz"))
        self.label.setText(_translate("TALLER2R", "Algoritmos de Robótica "))
        self.label_5.setText(_translate("TALLER2R", "Coordenadas "))
        self.Cordenadas.setText(_translate("TALLER2R", "GO!"))
        self.label_6.setText(_translate("TALLER2R", "Área de Trabajo"))
        self.Area_Trabajo.setText(_translate("TALLER2R", "AREA"))
        self.label_9.setText(_translate("TALLER2R", "Nombres"))
        self.Nico_boton.setText(_translate("TALLER2R", "NICOLAS"))
        self.Andres_boton.setText(_translate("TALLER2R", "ANDRES"))
        self.label_10.setText(_translate("TALLER2R", "Nombre Personalizado"))
        self.Nombreperso.setText(_translate("TALLER2R", "START"))
        self.label_11.setText(_translate("TALLER2R", "Logos"))
        self.Chevroletboton.setText(_translate("TALLER2R", "CHEVROLET"))
        self.renaultboton.setText(_translate("TALLER2R", "RENAULT"))
        self.kiaboton.setText(_translate("TALLER2R", "KIA"))
        self.mercedeboton.setText(_translate("TALLER2R", "MERCEDES"))
        self.label_12.setText(_translate("TALLER2R", "ROBOT"))
        self.label_13.setText(_translate("TALLER2R", "Gilber Alexander Cantor Quintero"))
        self.label_14.setText(_translate("TALLER2R", "Lheidy Barragan V"))
        self.label_15.setText(_translate("TALLER2R", "Kevin Sebastian Duenas Lozano"))
        self.Andres_boton_2.setText(_translate("TALLER2R", "GILBER"))
        self.Andres_boton_3.setText(_translate("TALLER2R", "LHEIDY"))
        self.Andres_boton_4.setText(_translate("TALLER2R", "KEVIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TALLER2R = QtWidgets.QDialog()
    ui = Ui_TALLER2R()
    ui.setupUi(TALLER2R)
    TALLER2R.show()
    sys.exit(app.exec_())
