#import RPi.GPIO as GPIO
#import time
from roboticstoolbox import *
from spatialmath.base import *
import math
import numpy as np
from sympy import *


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TALLER2R(object):
    def setupUi(self, TALLER2R):
        TALLER2R.setObjectName("TALLER2R")
        TALLER2R.resize(671, 438)
        self.label_4 = QtWidgets.QLabel(TALLER2R)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(TALLER2R)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(TALLER2R)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(TALLER2R)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(TALLER2R)
        self.label_8.setGeometry(QtCore.QRect(380, 10, 181, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TALLER3\IMAGENES\ecci.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(TALLER2R)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DISP = QtWidgets.QWidget(TALLER2R)
        self.DISP.setGeometry(QtCore.QRect(10, 200, 271, 181))
        self.DISP.setObjectName("DISP")
        self.label_5 = QtWidgets.QLabel(TALLER2R)
        self.label_5.setGeometry(QtCore.QRect(290, 110, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.X_LABEL = QtWidgets.QTextEdit(TALLER2R)
        self.X_LABEL.setGeometry(QtCore.QRect(310, 150, 71, 31))
        self.X_LABEL.setObjectName("X_LABEL")
        self.Y_LABEL = QtWidgets.QTextEdit(TALLER2R)
        self.Y_LABEL.setGeometry(QtCore.QRect(390, 150, 71, 31))
        self.Y_LABEL.setObjectName("Y_LABEL")
        self.Cordenadas = QtWidgets.QPushButton(TALLER2R)
        self.Cordenadas.setGeometry(QtCore.QRect(480, 150, 71, 31))
        self.Cordenadas.setObjectName("Cordenadas")
        self.label_6 = QtWidgets.QLabel(TALLER2R)
        self.label_6.setGeometry(QtCore.QRect(300, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Area_Trabajo = QtWidgets.QPushButton(TALLER2R)
        self.Area_Trabajo.setGeometry(QtCore.QRect(340, 220, 171, 31))
        self.Area_Trabajo.setObjectName("Area_Trabajo")
        self.label_9 = QtWidgets.QLabel(TALLER2R)
        self.label_9.setGeometry(QtCore.QRect(300, 250, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Nico_boton = QtWidgets.QPushButton(TALLER2R)
        self.Nico_boton.setGeometry(QtCore.QRect(370, 270, 61, 31))
        self.Nico_boton.setObjectName("Nico_boton")
        self.Andres_boton = QtWidgets.QPushButton(TALLER2R)
        self.Andres_boton.setGeometry(QtCore.QRect(450, 270, 51, 31))
        self.Andres_boton.setObjectName("Andres_boton")
        self.label_10 = QtWidgets.QLabel(TALLER2R)
        self.label_10.setGeometry(QtCore.QRect(300, 310, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.NOMBREP = QtWidgets.QTextEdit(TALLER2R)
        self.NOMBREP.setGeometry(QtCore.QRect(310, 330, 161, 31))
        self.NOMBREP.setObjectName("NOMBREP")
        self.Nombreperso = QtWidgets.QPushButton(TALLER2R)
        self.Nombreperso.setGeometry(QtCore.QRect(480, 330, 101, 31))
        self.Nombreperso.setObjectName("Nombreperso")
        self.label_11 = QtWidgets.QLabel(TALLER2R)
        self.label_11.setGeometry(QtCore.QRect(300, 360, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Chevroletboton = QtWidgets.QPushButton(TALLER2R)
        self.Chevroletboton.setGeometry(QtCore.QRect(310, 390, 71, 31))
        self.Chevroletboton.setObjectName("Chevroletboton")
        self.renaultboton = QtWidgets.QPushButton(TALLER2R)
        self.renaultboton.setGeometry(QtCore.QRect(400, 390, 61, 31))
        self.renaultboton.setObjectName("renaultboton")
        self.kiaboton = QtWidgets.QPushButton(TALLER2R)
        self.kiaboton.setGeometry(QtCore.QRect(480, 390, 51, 31))
        self.kiaboton.setObjectName("kiaboton")
        self.mercedeboton = QtWidgets.QPushButton(TALLER2R)
        self.mercedeboton.setGeometry(QtCore.QRect(560, 390, 71, 31))
        self.mercedeboton.setObjectName("mercedeboton")
        self.label_12 = QtWidgets.QLabel(TALLER2R)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(TALLER2R)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(TALLER2R)
        self.label_14.setGeometry(QtCore.QRect(20, 110, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(TALLER2R)
        self.label_15.setGeometry(QtCore.QRect(20, 130, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Gilber_boton = QtWidgets.QPushButton(TALLER2R)
        self.Gilber_boton.setGeometry(QtCore.QRect(510, 270, 51, 31))
        self.Gilber_boton.setObjectName("Gilber_boton")
        self.Lheidy_boton = QtWidgets.QPushButton(TALLER2R)
        self.Lheidy_boton.setGeometry(QtCore.QRect(310, 270, 51, 31))
        self.Lheidy_boton.setObjectName("Lheidy_boton")
        self.Kevin_boton = QtWidgets.QPushButton(TALLER2R)
        self.Kevin_boton.setGeometry(QtCore.QRect(580, 270, 51, 31))
        self.Kevin_boton.setObjectName("Kevin_boton")
        self.label_16 = QtWidgets.QLabel(TALLER2R)
        self.label_16.setGeometry(QtCore.QRect(310, 130, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(TALLER2R)
        self.label_17.setGeometry(QtCore.QRect(390, 130, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(TALLER2R)
        self.label_18.setGeometry(QtCore.QRect(560, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(TALLER2R)
        self.label_19.setGeometry(QtCore.QRect(560, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.teta1 = QtWidgets.QLabel(TALLER2R)
        self.teta1.setGeometry(QtCore.QRect(620, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta1.setFont(font)
        self.teta1.setText("")
        self.teta1.setObjectName("teta1")
        self.teta2 = QtWidgets.QLabel(TALLER2R)
        self.teta2.setGeometry(QtCore.QRect(620, 160, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta2.setFont(font)
        self.teta2.setText("")
        self.teta2.setObjectName("teta2")

        self.retranslateUi(TALLER2R)
        QtCore.QMetaObject.connectSlotsByName(TALLER2R)
        #----------------------------------------------------------------
        #Declaracion de puertos 
        #----------------------------------------------------------------
        # Set pin 11 as an output, and define as servo1 as PWM pin
        #GPIO.setup(11, GPIO.OUT)
        #self.servomotor1 = GPIO.PWM(11, 50)  # pin 11 for servo1, pulse 50Hz
        #GPIO.setup(12,GPIO.OUT)
        #self.servomotor2 = GPIO.PWM(12,50) # pin 12 for servo2, pulse 50Hz
        #----------------------------------------------------------------
        
        
        #----------------------------------------------------------------
        #Inicializar servos 
        #----------------------------------------------------------------
        #self.servomotor1.start(0)
        #self.servomotor2.start(0)       
        #----------------------------------------------------------------
        #----------------------------------------------------------------
        #Funcion para dibujar las coordeanadas  
        #----------------------------------------------------------------
        self.Area_Trabajo.clicked.connect(self.mostrar_area_de_trabajo)
        
        self.Cordenadas.clicked.connect(self.cinematica_inversa2r)
        

    def retranslateUi(self, TALLER2R):
        _translate = QtCore.QCoreApplication.translate
        TALLER2R.setWindowTitle(_translate("TALLER2R", "TALLER3"))
        self.label_4.setText(_translate("TALLER2R", "2024 - 1"))
        self.label_7.setText(_translate("TALLER2R", "Ingeniería Mecatrónica"))
        self.label_3.setText(_translate("TALLER2R", "Andrés Felipe Romero Medina"))
        self.label_2.setText(_translate("TALLER2R", "Nicolas Mejia Muñoz"))
        self.label.setText(_translate("TALLER2R", "Algoritmos de Robótica "))
        self.label_5.setText(_translate("TALLER2R", "Coordenadas "))
        self.Cordenadas.setText(_translate("TALLER2R", "GO!"))
        self.label_6.setText(_translate("TALLER2R", "Área de Trabajo"))
        self.Area_Trabajo.setText(_translate("TALLER2R", "AREA"))
        self.label_9.setText(_translate("TALLER2R", "Nombres"))
        self.Nico_boton.setText(_translate("TALLER2R", "NICOLAS"))
        self.Andres_boton.setText(_translate("TALLER2R", "ANDRES"))
        self.label_10.setText(_translate("TALLER2R", "Nombre Personalizado"))
        self.Nombreperso.setText(_translate("TALLER2R", "START"))
        self.label_11.setText(_translate("TALLER2R", "Logos"))
        self.Chevroletboton.setText(_translate("TALLER2R", "CHEVROLET"))
        self.renaultboton.setText(_translate("TALLER2R", "RENAULT"))
        self.kiaboton.setText(_translate("TALLER2R", "KIA"))
        self.mercedeboton.setText(_translate("TALLER2R", "MERCEDES"))
        self.label_12.setText(_translate("TALLER2R", "ROBOT"))
        self.label_13.setText(_translate("TALLER2R", "Gilber Alexander Cantor Quintero"))
        self.label_14.setText(_translate("TALLER2R", "Lheidy Barragan V"))
        self.label_15.setText(_translate("TALLER2R", "Kevin Sebastian Duenas Lozano"))
        self.Gilber_boton.setText(_translate("TALLER2R", "GILBER"))
        self.Lheidy_boton.setText(_translate("TALLER2R", "LHEIDY"))
        self.Kevin_boton.setText(_translate("TALLER2R", "KEVIN"))
        self.label_16.setText(_translate("TALLER2R", "Eje X"))
        self.label_17.setText(_translate("TALLER2R", "Eje Y"))
        self.label_18.setText(_translate("TALLER2R", "Servo_1"))
        self.label_19.setText(_translate("TALLER2R", "Servo_2"))
        
    def mostrar_area_de_trabajo(self):
          print("Imprimo area")
          angle1 = 150  
          self.servomotor1.ChangeDutyCycle(2 + (angle1 / 18))
          time.sleep(0.005)
          self.servomotor1.ChangeDutyCycle(0)
          angle2 = 150  
          self.servomotor2.ChangeDutyCycle(2 + (angle2 / 18))
          time.sleep(0.005)
          self.servomotor2.ChangeDutyCycle(0)
    
    def toma_coordenadas(self):
        print("Imprimo coordenadas")
    
    def cinematica_inversa2r(self):
        print("Imprimo cinematica inversa")  
    
        l1 = 10
        l2 = 10

        # Cinemática inversa
        Px = float(self.X_LABEL.toPlainText())
        Py = float(self.Y_LABEL.toPlainText())

        b = math.sqrt(Px**2+Py**2)
        # Theta 2
        cos_theta2 = (b**2-l2**2-l1**2)/(2*l1*l2)
        sen_theta2 = math.sqrt(1-(cos_theta2)**2)#(+)codo abajo y (-)codo arriba
        theta2 = math.atan2(sen_theta2, cos_theta2)
        print(f'theta 2 = {numpy.rad2deg(theta2):.4f}')
        # Theta 1
        alpha = math.atan2(Py,Px)
        phi = math.atan2(l2*sen_theta2, l1+l2*cos_theta2)
        theta1 = alpha - phi
        print(f'theta 1 = {numpy.rad2deg(theta1):.4f}')
        #-------------

        q1 = theta1
        q2 = theta2
        
        # Escribir los ángulos en los sliders de los servos
        self.servo1.setValue(int(np.rad2deg(theta1)))
        self.servo2.setValue(int(np.rad2deg(theta2)))

        # Actualizar los valores de theta1 y theta2 en los objetos teta1 y teta2
        self.teta1.setText(f"{np.rad2deg(theta1):.2f}")
        self.teta2.setText(f"{np.rad2deg(theta2):.2f}")
        #----------------------------------------------------------------
        R = []
        R.append(RevoluteDH(d=0, alpha=0, a=l1, offset=0))
        R.append(RevoluteDH(d=0, alpha=0, a=l2, offset=0))

        Robot = DHRobot(R, name='Bender')
        print(Robot)

        Robot.teach([q1, q2], 'rpy/zyx', limits=[-30,30,-30,30,-30,30])

        #zlim([-15,30]);

        MTH = Robot.fkine([q1,q2])
        print(MTH)
        print(f'Roll, Pitch, Yaw = {tr2rpy(MTH.R, 'deg', 'zyx')}')
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TALLER2R = QtWidgets.QDialog()
    ui = Ui_TALLER2R()
    ui.setupUi(TALLER2R)
    TALLER2R.show()
    sys.exit(app.exec_())
