
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 444)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 10, 181, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TALLER3\IMAGENES\ecci.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DISP = QtWidgets.QWidget(Dialog)
        self.DISP.setGeometry(QtCore.QRect(10, 180, 271, 181))
        self.DISP.setObjectName("DISP")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(290, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.X_LABEL = QtWidgets.QTextEdit(Dialog)
        self.X_LABEL.setGeometry(QtCore.QRect(310, 150, 71, 31))
        self.X_LABEL.setObjectName("X_LABEL")
        self.X_LABEL_2 = QtWidgets.QTextEdit(Dialog)
        self.X_LABEL_2.setGeometry(QtCore.QRect(390, 150, 71, 31))
        self.X_LABEL_2.setObjectName("X_LABEL_2")
        self.Cordenadas = QtWidgets.QPushButton(Dialog)
        self.Cordenadas.setGeometry(QtCore.QRect(480, 150, 71, 31))
        self.Cordenadas.setObjectName("Cordenadas")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(300, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Area_Trabajo = QtWidgets.QPushButton(Dialog)
        self.Area_Trabajo.setGeometry(QtCore.QRect(340, 220, 171, 31))
        self.Area_Trabajo.setObjectName("Area_Trabajo")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(300, 250, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Nico_boton = QtWidgets.QPushButton(Dialog)
        self.Nico_boton.setGeometry(QtCore.QRect(310, 270, 101, 31))
        self.Nico_boton.setObjectName("Nico_boton")
        self.Andres_boton = QtWidgets.QPushButton(Dialog)
        self.Andres_boton.setGeometry(QtCore.QRect(440, 270, 101, 31))
        self.Andres_boton.setObjectName("Andres_boton")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(300, 310, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.X_LABEL_3 = QtWidgets.QTextEdit(Dialog)
        self.X_LABEL_3.setGeometry(QtCore.QRect(310, 330, 161, 31))
        self.X_LABEL_3.setObjectName("X_LABEL_3")
        self.Nombreperso = QtWidgets.QPushButton(Dialog)
        self.Nombreperso.setGeometry(QtCore.QRect(480, 330, 101, 31))
        self.Nombreperso.setObjectName("Nombreperso")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(300, 360, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Chevroletboton = QtWidgets.QPushButton(Dialog)
        self.Chevroletboton.setGeometry(QtCore.QRect(300, 390, 71, 31))
        self.Chevroletboton.setObjectName("Chevroletboton")
        self.renaultboton = QtWidgets.QPushButton(Dialog)
        self.renaultboton.setGeometry(QtCore.QRect(380, 390, 61, 31))
        self.renaultboton.setObjectName("renaultboton")
        self.kiaboton = QtWidgets.QPushButton(Dialog)
        self.kiaboton.setGeometry(QtCore.QRect(450, 390, 51, 31))
        self.kiaboton.setObjectName("kiaboton")
        self.mercedeboton = QtWidgets.QPushButton(Dialog)
        self.mercedeboton.setGeometry(QtCore.QRect(510, 390, 71, 31))
        self.mercedeboton.setObjectName("mercedeboton")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 150, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "2024 - 1"))
        self.label_7.setText(_translate("Dialog", "Ingeniería Mecatrónica"))
        self.label_3.setText(_translate("Dialog", "Andrés Felipe Romero Medina"))
        self.label_2.setText(_translate("Dialog", "Nicolas Mejia Muñoz"))
        self.label.setText(_translate("Dialog", "Algoritmos de Robótica "))
        self.label_5.setText(_translate("Dialog", "Coordenadas "))
        self.Cordenadas.setText(_translate("Dialog", "GO!"))
        self.label_6.setText(_translate("Dialog", "Área de Trabajo"))
        self.Area_Trabajo.setText(_translate("Dialog", "AREA"))
        self.label_9.setText(_translate("Dialog", "Nombres"))
        self.Nico_boton.setText(_translate("Dialog", "NICOLAS"))
        self.Andres_boton.setText(_translate("Dialog", "ANDRES"))
        self.label_10.setText(_translate("Dialog", "Nombre Personalizado"))
        self.Nombreperso.setText(_translate("Dialog", "START"))
        self.label_11.setText(_translate("Dialog", "Logos"))
        self.Chevroletboton.setText(_translate("Dialog", "CHEVROLET"))
        self.renaultboton.setText(_translate("Dialog", "RENAULT"))
        self.kiaboton.setText(_translate("Dialog", "KIA"))
        self.mercedeboton.setText(_translate("Dialog", "MERCEDES"))
        self.label_12.setText(_translate("Dialog", "ROBOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
